development:
  adapter: postgresql
  encoding: utf8
  database: fodmapify_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: fodmapify_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: fodmapify_production
  pool: 5

cucumber:
  <<: *TEST